#%RAML 1.0 Trait
queryParameters:
  customerName:
    type: string
    required: true
    maxLength: 45
    minLength: 4
  branchname:
    type: string
    required: true
    maxLength: 10
    minLength: 4

    