#%RAML 1.0 Trait
account:
  put:
    body:
      application/json:
        example: {
          "s": "ddd"
        }
    responses:
      200:
        body:
          application/json:
            example: {
              "status": "sucess"
            }
       